events {}

http {
	server {
		listen 80;
		server_name helmbold.org;
		root /usr/share/nginx/html/main;
		index index.html;
	}

	server {
		listen 80;
		server_name about.helmbold.org;
		root /usr/share/nginx/html/about;
		index index.html;
	}
}
